-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS
LEFT JOIN BOOK B
ON BS.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC

