WITH RECURSIVE RECURSIVE_ECOLI_DATA AS (
    SELECT ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE, 1 AS LEVEL
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.SIZE_OF_COLONY, E.DIFFERENTIATION_DATE, E.GENOTYPE, RED.LEVEL + 1 AS LEVEL
    FROM ECOLI_DATA E
    INNER JOIN RECURSIVE_ECOLI_DATA RED
    ON E.PARENT_ID = RED.ID
)

SELECT ID
FROM RECURSIVE_ECOLI_DATA
WHERE LEVEL = 3
ORDER BY ID