SELECT A.CHILD_ID AS ID
     , A.CHILD_GENOTYPE AS GENOTYPE 
     , A.PARENT_GENOTYPE AS PARENT_GENOTYPE
FROM (
    SELECT ED.ID AS PARENT_ID 
         , ED2.ID AS CHILD_ID
         , ED.GENOTYPE AS PARENT_GENOTYPE
         , ED2.GENOTYPE AS CHILD_GENOTYPE
    FROM ECOLI_DATA ED
    LEFT JOIN ECOLI_DATA ED2
    ON ED.ID = ED2.PARENT_ID) A
WHERE PARENT_ID IS NOT NULL
  AND CHILD_ID IS NOT NULL
  AND PARENT_GENOTYPE & CHILD_GENOTYPE = PARENT_GENOTYPE
ORDER BY A.CHILD_ID
