-- 코드를 입력하세요
SELECT DISTINCT CR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CR
RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
ON CR.CAR_ID = CH.CAR_ID
WHERE CR.CAR_TYPE = '세단'
AND CH.START_DATE LIKE '2022-10%'
ORDER BY CR.CAR_ID DESC