-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', UGB.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) AS FILE_PATH
FROM (
   SELECT *
   FROM USED_GOODS_BOARD UGB
   ORDER BY VIEWS DESC
   LIMIT 1) UGB
LEFT JOIN USED_GOODS_FILE UGF
ON UGB.BOARD_ID = UGF.BOARD_ID
ORDER BY UGF.FILE_ID DESC